server.servlet.context-path=/sistema/api/v1
server.port=8080

spring.application.name=app_prod

service.products = json

# Configuracion Personalizada de la aplicacion
app.name=Sistema de Productos
app.version=0.0.1
app.autor=Desarrollo de Innovadores S.A
app.language=es
app.country=Mexico
